name: Project proposal
description: Proposal for a new project
labels: [new project]
body:
- type: markdown
  attributes:
    value: |
      Thank you for taking the time to fill out this project proposal!
- type: dropdown
  attributes:
    label: Programming language(s)
    description: What programming language(s) will the project be in?
    multiple: true
    options:
      - C
      - C++
      - HTML
      - TypeScript
- type: textarea
  attributes:
    label: Description
    description: Please elaborate on the project.
  validations:
    required: true
- type: textarea
  attributes:
    label: Motivation
    description: Why should this project be created?
  validations:
    required: true
- type: input
  attributes:
    label: Project name
    description: What would be the name of the project?
